name: pewobu
description: Custom design for all purpose list
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  carousel_slider: ^4.2.1
  flutter_fancy_tree_view: ^1.4.1
  flutter_native_splash: ^2.3.8
  gap: ^3.0.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  provider: ^6.1.1
  shared_preferences: ^2.0.15
  sized_context: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/profile_pic.png